[book]
authors = ["Qhy23"]
description = "辐射成像大赛信息平台"
language = "zh-CN"
multilingual = false
src = "./src"
title = "辐射成像大赛"

[preprocessor.katex]
after = ["links"]
output = "htmlAndMathml"
pre-render = true

[output.html]
additional-css = ["css/fontsize.css"]
git-repository-url = "https://github.com/thudep/RI-homepage"

[output.html.search]
boost-hierarchy = 2
boost-paragraph = 1
boost-title = 2
expand = true
heading-split-level = 2
limit-results = 20
use-boolean-and = true